#responses tags
HTTP__EXCEPTION_TAG__MISSING_PARAMS = '_MissingRequestParams_'
HTTP__EXCEPTION_TAG__NOT_PROPER_REQUEST_TYPE = '_BadRequestTypeForUrl_'
HTTP__EXCEPTION_TAG__NO_SUCH_SCRIPT_IN_STORAGE = '_ScriptDoesNotExist_'
HTTP__EXCEPTION_TAG__BAD_SCRIPT_REVISION = '_BadScriptRevision_'
HTTP__EXCEPTION_TAG__SCRIPT_ALREADY_IN_STORAGE = '_ScriptAlreadyInStorage_'
HTTP__EXCEPTION_TAG__NOT_SUPPORTED_REQUEST_TYPE = '_RequestTypeDoesNotSupported_'
HTTP__EXCEPTION_TAG__NOT_SUPPORTED_ACTION = '_NotSupportedAction_'

HTTP__OK_RESPONSE = '_OK_'

#request params names
REQUEST_PARAM_NAME__USER = 'user'
REQUEST_PARAM_NAME__NEW_SCRIPT_NAME = 'new_name'
REQUEST_PARAM_NAME_ACTION = 'action'
REQUEST_PARAM_NAME__SCRIPT_NAME = 'script_name'
REQUEST_PARAM_NAME__SCRIPT_REVISION = 'revision'

#response body configuration
JSON_INDENT = 2
JSON_ATTR_NAME__REVISION = 'revision'
JSON_ATTR_NAME__MODIFIED_DATE = 'modified_date'
JSON_ATTR_NAME__CHANGER = 'changer_user'

#storage default conf
STORAGE_DEFAULT_SCAN_PERIOD_MS = 2000
DEFAULT_STORAGE_SCRIPT_CREATOR_NAME = 'autostore'